<template>
  <a-menu
    :style="{ height: '100%' }"
    :show-collapse-button="true"
    :auto-open-selected="true"
    breakpoint="xl"
    :collapsible="true"
    :level-indent="34"
    @collapse="appStore.toggleMenu"
    accordion
    auto-open
    :open-keys="openKeys"
    :selected-keys="selectedKeys"
    @menu-item-click="onMenuItemClick"
    @sub-menu-click="onSubMenuClick"
  >
    <MenuRecursion :menu="menuTree" />
  </a-menu>
</template>

<script setup lang="ts">
import { MenuRecord } from '@/api/system/types';
import { useState } from '@/hooks/useState';
import { useAppStore } from '@/store/modules/app';
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import MenuRecursion from './menu-recursion.vue';

const appStore = useAppStore();
const router = useRouter();
const [selectedKeys, setSelectedKeys] = useState<string[]>([]);
const [openKeys, setOpenKeys] = useState<string[]>([]);

const onSubMenuClick = (_: string, openKeys: string[]) => {
  setOpenKeys(openKeys);
};

const onMenuItemClick = (key: string) => {
  setSelectedKeys([key]);
  router.push({ name: key });
};

const menuTree = ref<MenuRecord[]>([
  {
    id: '438122794715188614',
    name: '仪表盘',
    parent_id: '1',
    parent_ids: '',
    icon: 'icon-dashboard',
    path: 'dashboard',
    permission: '',
    type: 'catalog',
    method: '',
    component: '',
    link: '',
    visible: '',
    redirect: '',
    status: 'enable',
    sort: 1000,
    updated_at: 1651730269,
    children: [
      {
        id: '438127252807355782',
        name: '工作台',
        parent_id: '438122794715188614',
        parent_ids: '',
        icon: '',
        path: 'workplace',
        permission: '',
        type: 'menu',
        method: '',
        component: '',
        link: '',
        visible: '',
        redirect: '',
        status: 'enable',
        sort: 1000,
        updated_at: 1653376016,
      },
      {
        id: '438127303440993670',
        name: '实时监控',
        parent_id: '438122794715188614',
        parent_ids: '',
        icon: '',
        path: 'monitor',
        permission: '',
        type: 'menu',
        method: '',
        component: '',
        link: '',
        visible: '',
        redirect: '',
        status: 'enable',
        sort: 1000,
        updated_at: 1653376788,
      },
    ],
  },
  {
    id: '438128000718867846',
    name: '组织架构',
    parent_id: '1',
    parent_ids: '',
    icon: 'icon-user-group',
    path: 'system',
    permission: '',
    type: 'catalog',
    method: '',
    component: '',
    link: '',
    visible: '',
    redirect: '',
    status: 'enable',
    sort: 1000,
    updated_at: 1651730480,
    children: [
      {
        id: '438128025716919686',
        name: '用户管理',
        parent_id: '438128000718867846',
        parent_ids: '',
        icon: '',
        path: 'staff',
        permission: '',
        type: 'menu',
        method: '',
        component: '',
        link: '',
        visible: '',
        redirect: '',
        status: 'enable',
        sort: 1000,
        updated_at: 1651730419,
        children: [
          {
            id: '438129527898508678',
            name: '用户查询',
            parent_id: '438128025716919686',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651494348,
          },
          {
            id: '438129556151340422',
            name: '用户增加',
            parent_id: '438128025716919686',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651494365,
          },
          {
            id: '438129578968354182',
            name: '用户编辑',
            parent_id: '438128025716919686',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651494379,
          },
          {
            id: '438129802189213062',
            name: '用户删除',
            parent_id: '438128025716919686',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651494512,
          },
          {
            id: '438129829888396678',
            name: '用户详情',
            parent_id: '438128025716919686',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651494528,
          },
          {
            id: '438129858996866438',
            name: '用户导出',
            parent_id: '438128025716919686',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651494546,
          },
          {
            id: '438129929041743238',
            name: '用户状态选择器',
            parent_id: '438128025716919686',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651494587,
          },
          {
            id: '438129950952787334',
            name: '用户授权角色',
            parent_id: '438128025716919686',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651494600,
          },
          {
            id: '438129973971127686',
            name: '用户拥有角色',
            parent_id: '438128025716919686',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651494614,
          },
          {
            id: '438129997912214918',
            name: '用户授权数据',
            parent_id: '438128025716919686',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651494628,
          },
          {
            id: '438130027205234054',
            name: '用户修改密码',
            parent_id: '438128025716919686',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651494691,
          },
          {
            id: '438130048612961670',
            name: '用户修改状态',
            parent_id: '438128025716919686',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651494659,
          },
          {
            id: '438130070976990598',
            name: '用户修改头像',
            parent_id: '438128025716919686',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651494672,
          },
          {
            id: '438130088660176262',
            name: '用户重置密码',
            parent_id: '438128025716919686',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651494683,
          },
        ],
      },
      {
        id: '438128041571388806',
        name: '组织管理',
        parent_id: '438128000718867846',
        parent_ids: '',
        icon: '',
        path: 'organization',
        permission: '',
        type: 'menu',
        method: '',
        component: '',
        link: '',
        visible: '',
        redirect: '',
        status: 'enable',
        sort: 1000,
        updated_at: 1651730426,
        children: [
          {
            id: '438237346039598470',
            name: '组织查询',
            parent_id: '438128041571388806',
            parent_ids: '',
            icon: '',
            path: '',
            permission: '',
            type: 'button',
            method: '',
            component: '',
            link: '',
            visible: '',
            redirect: '',
            status: 'enable',
            sort: 1000,
            updated_at: 1651558613,
          },
        ],
      },
      {
        id: '438128058130500998',
        name: '职位管理',
        parent_id: '438128000718867846',
        parent_ids: '',
        icon: '',
        path: 'position',
        permission: '',
        type: 'menu',
        method: '',
        component: '',
        link: '',
        visible: '',
        redirect: '',
        status: 'enable',
        sort: 1000,
        updated_at: 1651730435,
      },
    ],
  },
  {
    id: '438667846482922886',
    name: '系统设置',
    parent_id: '1',
    parent_ids: '',
    icon: 'icon-settings',
    path: 'setting',
    permission: '',
    type: 'catalog',
    method: '',
    component: '',
    link: '',
    visible: '',
    redirect: '',
    status: 'enable',
    sort: 1000,
    updated_at: 1651815211,
    children: [
      {
        id: '438668093460319622',
        name: '字典管理',
        parent_id: '438667846482922886',
        parent_ids: '',
        icon: '',
        path: 'dictionary',
        permission: '',
        type: 'menu',
        method: '',
        component: '',
        link: '',
        visible: '',
        redirect: '',
        status: 'enable',
        sort: 1000,
        updated_at: 1651815358,
      },
      {
        id: '438668288277351814',
        name: '菜单管理',
        parent_id: '438667846482922886',
        parent_ids: '',
        icon: '',
        path: 'menu',
        permission: '',
        type: 'menu',
        method: '',
        component: '',
        link: '',
        visible: '',
        redirect: '',
        status: 'enable',
        sort: 1000,
        updated_at: 1651815474,
      },
      {
        id: '440412188746725377',
        name: '角色管理',
        parent_id: '438667846482922886',
        parent_ids: '',
        icon: '',
        path: 'role',
        permission: '',
        type: 'menu',
        method: '',
        component: '',
        link: '',
        visible: '',
        redirect: '',
        status: 'enable',
        sort: 1000,
        updated_at: 1652854920,
      },
    ],
  },
] as MenuRecord[]);
</script>
